---
# Handlers for MusicBox Player Role

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Restart player service
  ansible.builtin.systemd:
    name: musicbox-player
    state: restarted
  become: yes
