/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check if the API is running
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/stream/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream media file
         * @description Stream audio/video file with range request support
         */
        get: operations["getApiMediaStreamById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all media
         * @description Get all media items, optionally filtered by type
         */
        get: operations["getApiMedia"];
        put?: never;
        /**
         * Upload media file
         * @description Upload an audio file (MP3, M4A, FLAC, WAV, OGG). Metadata is extracted automatically.
         */
        post: operations["postApiMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get media by ID
         * @description Get a single media item by its ID
         */
        get: operations["getApiMediaById"];
        put?: never;
        post?: never;
        /**
         * Delete media
         * @description Delete a media item and its file from disk
         */
        delete: operations["deleteApiMediaById"];
        options?: never;
        head?: never;
        /**
         * Update media metadata
         * @description Update title and metadata for a media item
         */
        patch: operations["patchApiMediaById"];
        trace?: never;
    };
    "/api/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all playlists */
        get: operations["getApiPlaylists"];
        put?: never;
        /** Create playlist */
        post: operations["postApiPlaylists"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get playlist by ID
         * @description Get a playlist with its media items
         */
        get: operations["getApiPlaylistsById"];
        put?: never;
        post?: never;
        /** Delete playlist */
        delete: operations["deleteApiPlaylistsById"];
        options?: never;
        head?: never;
        /** Update playlist */
        patch: operations["patchApiPlaylistsById"];
        trace?: never;
    };
    "/api/playlists/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add media to playlist */
        post: operations["postApiPlaylistsByIdMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{id}/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove media from playlist */
        delete: operations["deleteApiPlaylistsByIdMediaByMediaId"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{id}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reorder playlist media
         * @description Pass array of media IDs in desired order
         */
        put: operations["putApiPlaylistsByIdReorder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all cards */
        get: operations["getApiCards"];
        put?: never;
        /** Create card */
        post: operations["postApiCards"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/lookup/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup card by UID
         * @description Get card details with associated content (media, playlist, or podcast)
         */
        get: operations["getApiCardsLookupByUid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get card by ID */
        get: operations["getApiCardsById"];
        put?: never;
        post?: never;
        /** Delete card */
        delete: operations["deleteApiCardsById"];
        options?: never;
        head?: never;
        /** Update card */
        patch: operations["patchApiCardsById"];
        trace?: never;
    };
    "/api/firmware/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get latest firmware info
         * @description Returns metadata about the currently deployed firmware
         */
        get: operations["getApiFirmwareLatest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/firmware/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download firmware binary
         * @description Download the firmware binary file for OTA updates
         */
        get: operations["getApiFirmwareDownload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
        };
    };
    getApiMediaStreamById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Partial content (range request) */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Media not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    getApiMedia: {
        parameters: {
            query?: {
                /** @description Filter by media type */
                type?: "song" | "podcast" | "soundmachine";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of media items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        /** @enum {string} */
                        type: "song" | "podcast" | "soundmachine";
                        title: string;
                        duration: number | null;
                        mimeType: string | null;
                        fileSize: number | null;
                        filePath: string;
                        metadata: unknown | null;
                        /** Format: date-time */
                        createdAt: string;
                    }[];
                };
            };
        };
    };
    postApiMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Audio file
                     */
                    file: string;
                    /** @description Optional title override */
                    title?: string;
                };
            };
        };
        responses: {
            /** @description Uploaded media item */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        /** @enum {string} */
                        type: "song" | "podcast" | "soundmachine";
                        title: string;
                        duration: number | null;
                        mimeType: string | null;
                        fileSize: number | null;
                        filePath: string;
                        metadata: unknown | null;
                        /** Format: date-time */
                        createdAt: string;
                    };
                };
            };
            /** @description Invalid file or request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    getApiMediaById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        /** @enum {string} */
                        type: "song" | "podcast" | "soundmachine";
                        title: string;
                        duration: number | null;
                        mimeType: string | null;
                        fileSize: number | null;
                        filePath: string;
                        metadata: unknown | null;
                        /** Format: date-time */
                        createdAt: string;
                    };
                };
            };
            /** @description Media not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    deleteApiMediaById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
            /** @description Media not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    patchApiMediaById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Updated media item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        /** @enum {string} */
                        type: "song" | "podcast" | "soundmachine";
                        title: string;
                        duration: number | null;
                        mimeType: string | null;
                        fileSize: number | null;
                        filePath: string;
                        metadata: unknown | null;
                        /** Format: date-time */
                        createdAt: string;
                    };
                };
            };
            /** @description Media not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    getApiPlaylists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of playlists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        name: string;
                        /** Format: date-time */
                        createdAt: string;
                    }[];
                };
            };
        };
    };
    postApiPlaylists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Created playlist */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        name: string;
                        /** Format: date-time */
                        createdAt: string;
                    };
                };
            };
        };
    };
    getApiPlaylistsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlist with media */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        name: string;
                        /** Format: date-time */
                        createdAt: string;
                        items: {
                            id: number;
                            /** @enum {string} */
                            type: "song" | "podcast" | "soundmachine";
                            title: string;
                            duration: number | null;
                            mimeType: string | null;
                            fileSize: number | null;
                            filePath: string;
                            metadata: unknown | null;
                            /** Format: date-time */
                            createdAt: string;
                            position: number;
                        }[];
                    };
                };
            };
            /** @description Playlist not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    deleteApiPlaylistsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
            /** @description Playlist not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    patchApiPlaylistsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated playlist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        name: string;
                        /** Format: date-time */
                        createdAt: string;
                    };
                };
            };
            /** @description Playlist not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    postApiPlaylistsByIdMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Added to playlist */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        playlistId: number;
                        mediaId: number;
                        position: number;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    deleteApiPlaylistsByIdMediaByMediaId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                mediaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    putApiPlaylistsByIdReorder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    getApiCards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of cards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        uid: string;
                        name: string | null;
                        mediaId: number | null;
                        playlistId: number | null;
                        podcastFeedId: number | null;
                        volume: number | null;
                        /** Format: date-time */
                        createdAt: string;
                    }[];
                };
            };
        };
    };
    postApiCards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created card */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        uid: string;
                        name: string | null;
                        mediaId: number | null;
                        playlistId: number | null;
                        podcastFeedId: number | null;
                        volume: number | null;
                        /** Format: date-time */
                        createdAt: string;
                    };
                };
            };
        };
    };
    getApiCardsLookupByUid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card with content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        type: "media" | "playlist" | "podcast" | "unmapped";
                        card: {
                            id: number;
                            uid: string;
                            name: string | null;
                            mediaId: number | null;
                            playlistId: number | null;
                            podcastFeedId: number | null;
                            volume: number | null;
                            /** Format: date-time */
                            createdAt: string;
                        };
                        volume?: number | null;
                        media?: {
                            id: number;
                            /** @enum {string} */
                            type: "song" | "podcast" | "soundmachine";
                            title: string;
                            duration: number | null;
                            mimeType: string | null;
                            fileSize: number | null;
                            filePath: string;
                            metadata: unknown | null;
                            /** Format: date-time */
                            createdAt: string;
                        };
                        playlist?: {
                            id: number;
                            name: string;
                            /** Format: date-time */
                            createdAt: string;
                        };
                        feed?: {
                            id: number;
                            name: string;
                            feedUrl: string;
                            imageUrl: string | null;
                            /** Format: date-time */
                            createdAt: string;
                        };
                    };
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        uid: string;
                    };
                };
            };
        };
    };
    getApiCardsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        uid: string;
                        name: string | null;
                        mediaId: number | null;
                        playlistId: number | null;
                        podcastFeedId: number | null;
                        volume: number | null;
                        /** Format: date-time */
                        createdAt: string;
                    };
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    deleteApiCardsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    patchApiCardsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated card */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        uid: string;
                        name: string | null;
                        mediaId: number | null;
                        playlistId: number | null;
                        podcastFeedId: number | null;
                        volume: number | null;
                        /** Format: date-time */
                        createdAt: string;
                    };
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    getApiFirmwareLatest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Firmware info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version: string;
                        sha256: string;
                        fileSize: number;
                    };
                };
            };
            /** @description No firmware available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    getApiFirmwareDownload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Firmware binary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description No firmware available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
}
