/**
 * Unified API client generation script
 *
 * Generates:
 * 1. OpenAPI spec from Hono routes
 * 2. TypeScript types for web client (openapi-typescript)
 * 3. C types for ESP32 client
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { execSync } from 'node:child_process'
import { generateSpecs } from 'hono-openapi'
import { createApp } from '../src/app.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const API_ROOT = path.join(__dirname, '..')
const WEB_ROOT = path.join(API_ROOT, '../web')
const ESP32_ROOT = path.join(API_ROOT, '../esp32')

const OPENAPI_PATH = path.join(API_ROOT, 'openapi.json')

async function generateOpenAPISpec() {
  console.log('Generating OpenAPI spec...')

  const app = createApp()
  const specs = await generateSpecs(app, {
    documentation: {
      openapi: '3.1.0',
      info: {
        title: 'MusicBox API',
        version: '1.0.0',
        description: 'API for MusicBox NFC music player',
      },
      servers: [{ url: 'http://localhost:3001', description: 'Local development' }],
    },
  })

  fs.writeFileSync(OPENAPI_PATH, JSON.stringify(specs, null, 2))
  console.log(`  ✓ OpenAPI spec: ${OPENAPI_PATH}`)

  return specs
}

async function generateTypeScriptClient() {
  console.log('Generating TypeScript client...')

  const outputPath = path.join(WEB_ROOT, 'src/lib/api-types.ts')

  // Use openapi-typescript to generate types
  execSync(`npx openapi-typescript ${OPENAPI_PATH} -o ${outputPath}`, {
    cwd: API_ROOT,
    stdio: 'pipe',
  })

  console.log(`  ✓ TypeScript types: ${outputPath}`)
}

async function generateCClient() {
  console.log('Generating C client for ESP32...')

  // Check if ESP32 package exists
  if (!fs.existsSync(ESP32_ROOT)) {
    console.log('  ⊘ ESP32 package not found, skipping')
    return
  }

  // TODO: Implement C type generation
  // This would generate structs and helpers for the ESP32 to parse API responses
  // For now, just create a placeholder

  const outputDir = path.join(ESP32_ROOT, 'src/generated')
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  const headerPath = path.join(outputDir, 'api_types.h')

  // Read the OpenAPI spec
  const spec = JSON.parse(fs.readFileSync(OPENAPI_PATH, 'utf-8'))

  // Generate a minimal C header with endpoint constants and basic structs
  const header = generateCHeader(spec)
  fs.writeFileSync(headerPath, header)

  console.log(`  ✓ C header: ${headerPath}`)
}

function generateCHeader(spec: any): string {
  const lines: string[] = [
    '/**',
    ' * Auto-generated API types for MusicBox ESP32 client',
    ' * DO NOT EDIT - Generated by generate-clients.ts',
    ' */',
    '',
    '#ifndef API_TYPES_H',
    '#define API_TYPES_H',
    '',
    '#include <stdint.h>',
    '#include <stdbool.h>',
    '',
    '// API Base URL (configure at runtime)',
    '#define API_DEFAULT_PORT 3001',
    '',
    '// Endpoint paths',
  ]

  // Generate endpoint constants
  for (const [path, _methods] of Object.entries(spec.paths || {})) {
    const constName = pathToConstName(path)
    lines.push(`#define API_PATH_${constName} "${path}"`)
  }

  lines.push('')
  lines.push('// Card lookup response types')
  lines.push('typedef enum {')
  lines.push('    CARD_TYPE_MEDIA = 0,')
  lines.push('    CARD_TYPE_PLAYLIST = 1,')
  lines.push('    CARD_TYPE_PODCAST = 2,')
  lines.push('    CARD_TYPE_UNMAPPED = 3')
  lines.push('} card_content_type_t;')
  lines.push('')

  lines.push('// Firmware info structure')
  lines.push('typedef struct {')
  lines.push('    char version[32];')
  lines.push('    char sha256[65];')
  lines.push('    uint32_t file_size;')
  lines.push('} firmware_info_t;')
  lines.push('')

  lines.push('// Card lookup response (simplified)')
  lines.push('typedef struct {')
  lines.push('    card_content_type_t type;')
  lines.push('    int32_t card_id;')
  lines.push('    int32_t content_id;  // media_id, playlist_id, or podcast_feed_id')
  lines.push('    int8_t volume;       // -1 if not set')
  lines.push('} card_lookup_result_t;')
  lines.push('')

  lines.push('#endif // API_TYPES_H')
  lines.push('')

  return lines.join('\n')
}

function pathToConstName(path: string): string {
  return path
    .replace(/^\//, '')
    .replace(/\{[^}]+\}/g, 'BY_PARAM')
    .replace(/[\/\-]/g, '_')
    .toUpperCase()
}

async function main() {
  console.log('=== MusicBox API Client Generation ===\n')

  try {
    await generateOpenAPISpec()
    await generateTypeScriptClient()
    await generateCClient()

    console.log('\n✓ All clients generated successfully')
  } catch (error) {
    console.error('\n✗ Generation failed:', error)
    process.exit(1)
  }
}

main()
