[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; N16R8 variant: 16MB flash, 8MB Octal PSRAM
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi

lib_deps =
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12
    adafruit/Adafruit PN532@^1.3.4
    lennarthennigs/Button2@^2.3.2
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM

; SPIFFS filesystem for system sounds
board_build.filesystem = spiffs
