/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/_library'
import { Route as LibraryIndexRouteImport } from './routes/_library/index'
import { Route as LibraryPlaylistsRouteImport } from './routes/_library/playlists'

const LibraryRoute = LibraryRouteImport.update({
  id: '/_library',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryPlaylistsRoute = LibraryPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LibraryIndexRoute
  '/playlists': typeof LibraryPlaylistsRoute
}
export interface FileRoutesByTo {
  '/playlists': typeof LibraryPlaylistsRoute
  '/': typeof LibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_library': typeof LibraryRouteWithChildren
  '/_library/playlists': typeof LibraryPlaylistsRoute
  '/_library/': typeof LibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/playlists'
  fileRoutesByTo: FileRoutesByTo
  to: '/playlists' | '/'
  id: '__root__' | '/_library' | '/_library/playlists' | '/_library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LibraryRoute: typeof LibraryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_library': {
      id: '/_library'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/': {
      id: '/_library/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/_library/playlists': {
      id: '/_library/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof LibraryPlaylistsRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface LibraryRouteChildren {
  LibraryPlaylistsRoute: typeof LibraryPlaylistsRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryPlaylistsRoute: LibraryPlaylistsRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LibraryRoute: LibraryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
