/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/_library'
import { Route as LibraryIndexRouteImport } from './routes/_library/index'
import { Route as LibraryPodcastsRouteImport } from './routes/_library/podcasts'
import { Route as LibraryPlaylistsRouteImport } from './routes/_library/playlists'
import { Route as LibraryDevicesRouteImport } from './routes/_library/devices'
import { Route as LibraryCardsRouteImport } from './routes/_library/cards'
import { Route as LibraryAddSongsRouteImport } from './routes/_library/add-songs'
import { Route as LibraryPlaylistsIndexRouteImport } from './routes/_library/playlists.index'
import { Route as ApiSoundsFilenameRouteImport } from './routes/api/sounds/$filename'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiFirmwareLatestRouteImport } from './routes/api/firmware/latest'
import { Route as ApiFirmwareDownloadRouteImport } from './routes/api/firmware/download'
import { Route as ApiDeviceConfigRouteImport } from './routes/api/device/config'
import { Route as LibraryPlaylistsPlaylistIdRouteImport } from './routes/_library/playlists.$playlistId'
import { Route as ApiSoundmachineConfigMacRouteImport } from './routes/api/soundmachine/config/$mac'
import { Route as ApiPlaylistsStreamIdRouteImport } from './routes/api/playlists/stream/$id'
import { Route as ApiMediaStreamIdRouteImport } from './routes/api/media/stream/$id'
import { Route as ApiCardsLookupUidRouteImport } from './routes/api/cards/lookup/$uid'

const LibraryRoute = LibraryRouteImport.update({
  id: '/_library',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryPodcastsRoute = LibraryPodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryPlaylistsRoute = LibraryPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryDevicesRoute = LibraryDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryCardsRoute = LibraryCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryAddSongsRoute = LibraryAddSongsRouteImport.update({
  id: '/add-songs',
  path: '/add-songs',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryPlaylistsIndexRoute = LibraryPlaylistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryPlaylistsRoute,
} as any)
const ApiSoundsFilenameRoute = ApiSoundsFilenameRouteImport.update({
  id: '/api/sounds/$filename',
  path: '/api/sounds/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirmwareLatestRoute = ApiFirmwareLatestRouteImport.update({
  id: '/api/firmware/latest',
  path: '/api/firmware/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirmwareDownloadRoute = ApiFirmwareDownloadRouteImport.update({
  id: '/api/firmware/download',
  path: '/api/firmware/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeviceConfigRoute = ApiDeviceConfigRouteImport.update({
  id: '/api/device/config',
  path: '/api/device/config',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPlaylistsPlaylistIdRoute =
  LibraryPlaylistsPlaylistIdRouteImport.update({
    id: '/$playlistId',
    path: '/$playlistId',
    getParentRoute: () => LibraryPlaylistsRoute,
  } as any)
const ApiSoundmachineConfigMacRoute =
  ApiSoundmachineConfigMacRouteImport.update({
    id: '/api/soundmachine/config/$mac',
    path: '/api/soundmachine/config/$mac',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlaylistsStreamIdRoute = ApiPlaylistsStreamIdRouteImport.update({
  id: '/api/playlists/stream/$id',
  path: '/api/playlists/stream/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaStreamIdRoute = ApiMediaStreamIdRouteImport.update({
  id: '/api/media/stream/$id',
  path: '/api/media/stream/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardsLookupUidRoute = ApiCardsLookupUidRouteImport.update({
  id: '/api/cards/lookup/$uid',
  path: '/api/cards/lookup/$uid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LibraryIndexRoute
  '/add-songs': typeof LibraryAddSongsRoute
  '/cards': typeof LibraryCardsRoute
  '/devices': typeof LibraryDevicesRoute
  '/playlists': typeof LibraryPlaylistsRouteWithChildren
  '/podcasts': typeof LibraryPodcastsRoute
  '/playlists/$playlistId': typeof LibraryPlaylistsPlaylistIdRoute
  '/api/device/config': typeof ApiDeviceConfigRoute
  '/api/firmware/download': typeof ApiFirmwareDownloadRoute
  '/api/firmware/latest': typeof ApiFirmwareLatestRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/sounds/$filename': typeof ApiSoundsFilenameRoute
  '/playlists/': typeof LibraryPlaylistsIndexRoute
  '/api/cards/lookup/$uid': typeof ApiCardsLookupUidRoute
  '/api/media/stream/$id': typeof ApiMediaStreamIdRoute
  '/api/playlists/stream/$id': typeof ApiPlaylistsStreamIdRoute
  '/api/soundmachine/config/$mac': typeof ApiSoundmachineConfigMacRoute
}
export interface FileRoutesByTo {
  '/add-songs': typeof LibraryAddSongsRoute
  '/cards': typeof LibraryCardsRoute
  '/devices': typeof LibraryDevicesRoute
  '/podcasts': typeof LibraryPodcastsRoute
  '/': typeof LibraryIndexRoute
  '/playlists/$playlistId': typeof LibraryPlaylistsPlaylistIdRoute
  '/api/device/config': typeof ApiDeviceConfigRoute
  '/api/firmware/download': typeof ApiFirmwareDownloadRoute
  '/api/firmware/latest': typeof ApiFirmwareLatestRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/sounds/$filename': typeof ApiSoundsFilenameRoute
  '/playlists': typeof LibraryPlaylistsIndexRoute
  '/api/cards/lookup/$uid': typeof ApiCardsLookupUidRoute
  '/api/media/stream/$id': typeof ApiMediaStreamIdRoute
  '/api/playlists/stream/$id': typeof ApiPlaylistsStreamIdRoute
  '/api/soundmachine/config/$mac': typeof ApiSoundmachineConfigMacRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_library': typeof LibraryRouteWithChildren
  '/_library/add-songs': typeof LibraryAddSongsRoute
  '/_library/cards': typeof LibraryCardsRoute
  '/_library/devices': typeof LibraryDevicesRoute
  '/_library/playlists': typeof LibraryPlaylistsRouteWithChildren
  '/_library/podcasts': typeof LibraryPodcastsRoute
  '/_library/': typeof LibraryIndexRoute
  '/_library/playlists/$playlistId': typeof LibraryPlaylistsPlaylistIdRoute
  '/api/device/config': typeof ApiDeviceConfigRoute
  '/api/firmware/download': typeof ApiFirmwareDownloadRoute
  '/api/firmware/latest': typeof ApiFirmwareLatestRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/sounds/$filename': typeof ApiSoundsFilenameRoute
  '/_library/playlists/': typeof LibraryPlaylistsIndexRoute
  '/api/cards/lookup/$uid': typeof ApiCardsLookupUidRoute
  '/api/media/stream/$id': typeof ApiMediaStreamIdRoute
  '/api/playlists/stream/$id': typeof ApiPlaylistsStreamIdRoute
  '/api/soundmachine/config/$mac': typeof ApiSoundmachineConfigMacRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-songs'
    | '/cards'
    | '/devices'
    | '/playlists'
    | '/podcasts'
    | '/playlists/$playlistId'
    | '/api/device/config'
    | '/api/firmware/download'
    | '/api/firmware/latest'
    | '/api/media/upload'
    | '/api/sounds/$filename'
    | '/playlists/'
    | '/api/cards/lookup/$uid'
    | '/api/media/stream/$id'
    | '/api/playlists/stream/$id'
    | '/api/soundmachine/config/$mac'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/add-songs'
    | '/cards'
    | '/devices'
    | '/podcasts'
    | '/'
    | '/playlists/$playlistId'
    | '/api/device/config'
    | '/api/firmware/download'
    | '/api/firmware/latest'
    | '/api/media/upload'
    | '/api/sounds/$filename'
    | '/playlists'
    | '/api/cards/lookup/$uid'
    | '/api/media/stream/$id'
    | '/api/playlists/stream/$id'
    | '/api/soundmachine/config/$mac'
  id:
    | '__root__'
    | '/_library'
    | '/_library/add-songs'
    | '/_library/cards'
    | '/_library/devices'
    | '/_library/playlists'
    | '/_library/podcasts'
    | '/_library/'
    | '/_library/playlists/$playlistId'
    | '/api/device/config'
    | '/api/firmware/download'
    | '/api/firmware/latest'
    | '/api/media/upload'
    | '/api/sounds/$filename'
    | '/_library/playlists/'
    | '/api/cards/lookup/$uid'
    | '/api/media/stream/$id'
    | '/api/playlists/stream/$id'
    | '/api/soundmachine/config/$mac'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LibraryRoute: typeof LibraryRouteWithChildren
  ApiDeviceConfigRoute: typeof ApiDeviceConfigRoute
  ApiFirmwareDownloadRoute: typeof ApiFirmwareDownloadRoute
  ApiFirmwareLatestRoute: typeof ApiFirmwareLatestRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiSoundsFilenameRoute: typeof ApiSoundsFilenameRoute
  ApiCardsLookupUidRoute: typeof ApiCardsLookupUidRoute
  ApiMediaStreamIdRoute: typeof ApiMediaStreamIdRoute
  ApiPlaylistsStreamIdRoute: typeof ApiPlaylistsStreamIdRoute
  ApiSoundmachineConfigMacRoute: typeof ApiSoundmachineConfigMacRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_library': {
      id: '/_library'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/': {
      id: '/_library/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/_library/podcasts': {
      id: '/_library/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof LibraryPodcastsRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/_library/playlists': {
      id: '/_library/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof LibraryPlaylistsRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/_library/devices': {
      id: '/_library/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof LibraryDevicesRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/_library/cards': {
      id: '/_library/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof LibraryCardsRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/_library/add-songs': {
      id: '/_library/add-songs'
      path: '/add-songs'
      fullPath: '/add-songs'
      preLoaderRoute: typeof LibraryAddSongsRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/_library/playlists/': {
      id: '/_library/playlists/'
      path: '/'
      fullPath: '/playlists/'
      preLoaderRoute: typeof LibraryPlaylistsIndexRouteImport
      parentRoute: typeof LibraryPlaylistsRoute
    }
    '/api/sounds/$filename': {
      id: '/api/sounds/$filename'
      path: '/api/sounds/$filename'
      fullPath: '/api/sounds/$filename'
      preLoaderRoute: typeof ApiSoundsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firmware/latest': {
      id: '/api/firmware/latest'
      path: '/api/firmware/latest'
      fullPath: '/api/firmware/latest'
      preLoaderRoute: typeof ApiFirmwareLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firmware/download': {
      id: '/api/firmware/download'
      path: '/api/firmware/download'
      fullPath: '/api/firmware/download'
      preLoaderRoute: typeof ApiFirmwareDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device/config': {
      id: '/api/device/config'
      path: '/api/device/config'
      fullPath: '/api/device/config'
      preLoaderRoute: typeof ApiDeviceConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/playlists/$playlistId': {
      id: '/_library/playlists/$playlistId'
      path: '/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof LibraryPlaylistsPlaylistIdRouteImport
      parentRoute: typeof LibraryPlaylistsRoute
    }
    '/api/soundmachine/config/$mac': {
      id: '/api/soundmachine/config/$mac'
      path: '/api/soundmachine/config/$mac'
      fullPath: '/api/soundmachine/config/$mac'
      preLoaderRoute: typeof ApiSoundmachineConfigMacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playlists/stream/$id': {
      id: '/api/playlists/stream/$id'
      path: '/api/playlists/stream/$id'
      fullPath: '/api/playlists/stream/$id'
      preLoaderRoute: typeof ApiPlaylistsStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/stream/$id': {
      id: '/api/media/stream/$id'
      path: '/api/media/stream/$id'
      fullPath: '/api/media/stream/$id'
      preLoaderRoute: typeof ApiMediaStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cards/lookup/$uid': {
      id: '/api/cards/lookup/$uid'
      path: '/api/cards/lookup/$uid'
      fullPath: '/api/cards/lookup/$uid'
      preLoaderRoute: typeof ApiCardsLookupUidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LibraryPlaylistsRouteChildren {
  LibraryPlaylistsPlaylistIdRoute: typeof LibraryPlaylistsPlaylistIdRoute
  LibraryPlaylistsIndexRoute: typeof LibraryPlaylistsIndexRoute
}

const LibraryPlaylistsRouteChildren: LibraryPlaylistsRouteChildren = {
  LibraryPlaylistsPlaylistIdRoute: LibraryPlaylistsPlaylistIdRoute,
  LibraryPlaylistsIndexRoute: LibraryPlaylistsIndexRoute,
}

const LibraryPlaylistsRouteWithChildren =
  LibraryPlaylistsRoute._addFileChildren(LibraryPlaylistsRouteChildren)

interface LibraryRouteChildren {
  LibraryAddSongsRoute: typeof LibraryAddSongsRoute
  LibraryCardsRoute: typeof LibraryCardsRoute
  LibraryDevicesRoute: typeof LibraryDevicesRoute
  LibraryPlaylistsRoute: typeof LibraryPlaylistsRouteWithChildren
  LibraryPodcastsRoute: typeof LibraryPodcastsRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryAddSongsRoute: LibraryAddSongsRoute,
  LibraryCardsRoute: LibraryCardsRoute,
  LibraryDevicesRoute: LibraryDevicesRoute,
  LibraryPlaylistsRoute: LibraryPlaylistsRouteWithChildren,
  LibraryPodcastsRoute: LibraryPodcastsRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LibraryRoute: LibraryRouteWithChildren,
  ApiDeviceConfigRoute: ApiDeviceConfigRoute,
  ApiFirmwareDownloadRoute: ApiFirmwareDownloadRoute,
  ApiFirmwareLatestRoute: ApiFirmwareLatestRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiSoundsFilenameRoute: ApiSoundsFilenameRoute,
  ApiCardsLookupUidRoute: ApiCardsLookupUidRoute,
  ApiMediaStreamIdRoute: ApiMediaStreamIdRoute,
  ApiPlaylistsStreamIdRoute: ApiPlaylistsStreamIdRoute,
  ApiSoundmachineConfigMacRoute: ApiSoundmachineConfigMacRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
