/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/_library'
import { Route as LibraryIndexRouteImport } from './routes/_library/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as LibraryPodcastsRouteImport } from './routes/_library/podcasts'
import { Route as LibraryDownloadsRouteImport } from './routes/_library/downloads'
import { Route as LibraryDevicesRouteImport } from './routes/_library/devices'
import { Route as LibraryCardsRouteImport } from './routes/_library/cards'
import { Route as ApiStreamSongIdRouteImport } from './routes/api/stream/$songId'
import { Route as ApiPlayerVersionRouteImport } from './routes/api/player/version'
import { Route as ApiPlayerDownloadRouteImport } from './routes/api/player/download'
import { Route as ApiNfcScanRouteImport } from './routes/api/nfc/scan'
import { Route as ApiDevicesHeartbeatRouteImport } from './routes/api/devices/heartbeat'
import { Route as LibraryPlaylistIdRouteImport } from './routes/_library/playlist.$id'
import { Route as ApiDevicesRegisterIndexRouteImport } from './routes/api/devices/register/index'
import { Route as ApiStreamEpisodeEpisodeIdRouteImport } from './routes/api/stream/episode/$episodeId'
import { Route as ApiDevicesRegisterDeviceIdStatusRouteImport } from './routes/api/devices/register/$deviceId/status'
import { Route as ApiDevicesRegisterDeviceIdSshReadyRouteImport } from './routes/api/devices/register/$deviceId/ssh-ready'

const LibraryRoute = LibraryRouteImport.update({
  id: '/_library',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPodcastsRoute = LibraryPodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryDownloadsRoute = LibraryDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryDevicesRoute = LibraryDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryCardsRoute = LibraryCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => LibraryRoute,
} as any)
const ApiStreamSongIdRoute = ApiStreamSongIdRouteImport.update({
  id: '/api/stream/$songId',
  path: '/api/stream/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerVersionRoute = ApiPlayerVersionRouteImport.update({
  id: '/api/player/version',
  path: '/api/player/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerDownloadRoute = ApiPlayerDownloadRouteImport.update({
  id: '/api/player/download',
  path: '/api/player/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNfcScanRoute = ApiNfcScanRouteImport.update({
  id: '/api/nfc/scan',
  path: '/api/nfc/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesHeartbeatRoute = ApiDevicesHeartbeatRouteImport.update({
  id: '/api/devices/heartbeat',
  path: '/api/devices/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPlaylistIdRoute = LibraryPlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => LibraryRoute,
} as any)
const ApiDevicesRegisterIndexRoute = ApiDevicesRegisterIndexRouteImport.update({
  id: '/api/devices/register/',
  path: '/api/devices/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamEpisodeEpisodeIdRoute =
  ApiStreamEpisodeEpisodeIdRouteImport.update({
    id: '/api/stream/episode/$episodeId',
    path: '/api/stream/episode/$episodeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDevicesRegisterDeviceIdStatusRoute =
  ApiDevicesRegisterDeviceIdStatusRouteImport.update({
    id: '/api/devices/register/$deviceId/status',
    path: '/api/devices/register/$deviceId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDevicesRegisterDeviceIdSshReadyRoute =
  ApiDevicesRegisterDeviceIdSshReadyRouteImport.update({
    id: '/api/devices/register/$deviceId/ssh-ready',
    path: '/api/devices/register/$deviceId/ssh-ready',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/cards': typeof LibraryCardsRoute
  '/devices': typeof LibraryDevicesRoute
  '/downloads': typeof LibraryDownloadsRoute
  '/podcasts': typeof LibraryPodcastsRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof LibraryIndexRoute
  '/playlist/$id': typeof LibraryPlaylistIdRoute
  '/api/devices/heartbeat': typeof ApiDevicesHeartbeatRoute
  '/api/nfc/scan': typeof ApiNfcScanRoute
  '/api/player/download': typeof ApiPlayerDownloadRoute
  '/api/player/version': typeof ApiPlayerVersionRoute
  '/api/stream/$songId': typeof ApiStreamSongIdRoute
  '/api/stream/episode/$episodeId': typeof ApiStreamEpisodeEpisodeIdRoute
  '/api/devices/register': typeof ApiDevicesRegisterIndexRoute
  '/api/devices/register/$deviceId/ssh-ready': typeof ApiDevicesRegisterDeviceIdSshReadyRoute
  '/api/devices/register/$deviceId/status': typeof ApiDevicesRegisterDeviceIdStatusRoute
}
export interface FileRoutesByTo {
  '/cards': typeof LibraryCardsRoute
  '/devices': typeof LibraryDevicesRoute
  '/downloads': typeof LibraryDownloadsRoute
  '/podcasts': typeof LibraryPodcastsRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof LibraryIndexRoute
  '/playlist/$id': typeof LibraryPlaylistIdRoute
  '/api/devices/heartbeat': typeof ApiDevicesHeartbeatRoute
  '/api/nfc/scan': typeof ApiNfcScanRoute
  '/api/player/download': typeof ApiPlayerDownloadRoute
  '/api/player/version': typeof ApiPlayerVersionRoute
  '/api/stream/$songId': typeof ApiStreamSongIdRoute
  '/api/stream/episode/$episodeId': typeof ApiStreamEpisodeEpisodeIdRoute
  '/api/devices/register': typeof ApiDevicesRegisterIndexRoute
  '/api/devices/register/$deviceId/ssh-ready': typeof ApiDevicesRegisterDeviceIdSshReadyRoute
  '/api/devices/register/$deviceId/status': typeof ApiDevicesRegisterDeviceIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_library': typeof LibraryRouteWithChildren
  '/_library/cards': typeof LibraryCardsRoute
  '/_library/devices': typeof LibraryDevicesRoute
  '/_library/downloads': typeof LibraryDownloadsRoute
  '/_library/podcasts': typeof LibraryPodcastsRoute
  '/api/health': typeof ApiHealthRoute
  '/_library/': typeof LibraryIndexRoute
  '/_library/playlist/$id': typeof LibraryPlaylistIdRoute
  '/api/devices/heartbeat': typeof ApiDevicesHeartbeatRoute
  '/api/nfc/scan': typeof ApiNfcScanRoute
  '/api/player/download': typeof ApiPlayerDownloadRoute
  '/api/player/version': typeof ApiPlayerVersionRoute
  '/api/stream/$songId': typeof ApiStreamSongIdRoute
  '/api/stream/episode/$episodeId': typeof ApiStreamEpisodeEpisodeIdRoute
  '/api/devices/register/': typeof ApiDevicesRegisterIndexRoute
  '/api/devices/register/$deviceId/ssh-ready': typeof ApiDevicesRegisterDeviceIdSshReadyRoute
  '/api/devices/register/$deviceId/status': typeof ApiDevicesRegisterDeviceIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/cards'
    | '/devices'
    | '/downloads'
    | '/podcasts'
    | '/api/health'
    | '/'
    | '/playlist/$id'
    | '/api/devices/heartbeat'
    | '/api/nfc/scan'
    | '/api/player/download'
    | '/api/player/version'
    | '/api/stream/$songId'
    | '/api/stream/episode/$episodeId'
    | '/api/devices/register'
    | '/api/devices/register/$deviceId/ssh-ready'
    | '/api/devices/register/$deviceId/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cards'
    | '/devices'
    | '/downloads'
    | '/podcasts'
    | '/api/health'
    | '/'
    | '/playlist/$id'
    | '/api/devices/heartbeat'
    | '/api/nfc/scan'
    | '/api/player/download'
    | '/api/player/version'
    | '/api/stream/$songId'
    | '/api/stream/episode/$episodeId'
    | '/api/devices/register'
    | '/api/devices/register/$deviceId/ssh-ready'
    | '/api/devices/register/$deviceId/status'
  id:
    | '__root__'
    | '/_library'
    | '/_library/cards'
    | '/_library/devices'
    | '/_library/downloads'
    | '/_library/podcasts'
    | '/api/health'
    | '/_library/'
    | '/_library/playlist/$id'
    | '/api/devices/heartbeat'
    | '/api/nfc/scan'
    | '/api/player/download'
    | '/api/player/version'
    | '/api/stream/$songId'
    | '/api/stream/episode/$episodeId'
    | '/api/devices/register/'
    | '/api/devices/register/$deviceId/ssh-ready'
    | '/api/devices/register/$deviceId/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LibraryRoute: typeof LibraryRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiDevicesHeartbeatRoute: typeof ApiDevicesHeartbeatRoute
  ApiNfcScanRoute: typeof ApiNfcScanRoute
  ApiPlayerDownloadRoute: typeof ApiPlayerDownloadRoute
  ApiPlayerVersionRoute: typeof ApiPlayerVersionRoute
  ApiStreamSongIdRoute: typeof ApiStreamSongIdRoute
  ApiStreamEpisodeEpisodeIdRoute: typeof ApiStreamEpisodeEpisodeIdRoute
  ApiDevicesRegisterIndexRoute: typeof ApiDevicesRegisterIndexRoute
  ApiDevicesRegisterDeviceIdSshReadyRoute: typeof ApiDevicesRegisterDeviceIdSshReadyRoute
  ApiDevicesRegisterDeviceIdStatusRoute: typeof ApiDevicesRegisterDeviceIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_library': {
      id: '/_library'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/': {
      id: '/_library/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/podcasts': {
      id: '/_library/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof LibraryPodcastsRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/_library/downloads': {
      id: '/_library/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof LibraryDownloadsRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/_library/devices': {
      id: '/_library/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof LibraryDevicesRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/_library/cards': {
      id: '/_library/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof LibraryCardsRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/api/stream/$songId': {
      id: '/api/stream/$songId'
      path: '/api/stream/$songId'
      fullPath: '/api/stream/$songId'
      preLoaderRoute: typeof ApiStreamSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/version': {
      id: '/api/player/version'
      path: '/api/player/version'
      fullPath: '/api/player/version'
      preLoaderRoute: typeof ApiPlayerVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/download': {
      id: '/api/player/download'
      path: '/api/player/download'
      fullPath: '/api/player/download'
      preLoaderRoute: typeof ApiPlayerDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nfc/scan': {
      id: '/api/nfc/scan'
      path: '/api/nfc/scan'
      fullPath: '/api/nfc/scan'
      preLoaderRoute: typeof ApiNfcScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/heartbeat': {
      id: '/api/devices/heartbeat'
      path: '/api/devices/heartbeat'
      fullPath: '/api/devices/heartbeat'
      preLoaderRoute: typeof ApiDevicesHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/playlist/$id': {
      id: '/_library/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof LibraryPlaylistIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/api/devices/register/': {
      id: '/api/devices/register/'
      path: '/api/devices/register'
      fullPath: '/api/devices/register'
      preLoaderRoute: typeof ApiDevicesRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/episode/$episodeId': {
      id: '/api/stream/episode/$episodeId'
      path: '/api/stream/episode/$episodeId'
      fullPath: '/api/stream/episode/$episodeId'
      preLoaderRoute: typeof ApiStreamEpisodeEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/register/$deviceId/status': {
      id: '/api/devices/register/$deviceId/status'
      path: '/api/devices/register/$deviceId/status'
      fullPath: '/api/devices/register/$deviceId/status'
      preLoaderRoute: typeof ApiDevicesRegisterDeviceIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/register/$deviceId/ssh-ready': {
      id: '/api/devices/register/$deviceId/ssh-ready'
      path: '/api/devices/register/$deviceId/ssh-ready'
      fullPath: '/api/devices/register/$deviceId/ssh-ready'
      preLoaderRoute: typeof ApiDevicesRegisterDeviceIdSshReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LibraryRouteChildren {
  LibraryCardsRoute: typeof LibraryCardsRoute
  LibraryDevicesRoute: typeof LibraryDevicesRoute
  LibraryDownloadsRoute: typeof LibraryDownloadsRoute
  LibraryPodcastsRoute: typeof LibraryPodcastsRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  LibraryPlaylistIdRoute: typeof LibraryPlaylistIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryCardsRoute: LibraryCardsRoute,
  LibraryDevicesRoute: LibraryDevicesRoute,
  LibraryDownloadsRoute: LibraryDownloadsRoute,
  LibraryPodcastsRoute: LibraryPodcastsRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  LibraryPlaylistIdRoute: LibraryPlaylistIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LibraryRoute: LibraryRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiDevicesHeartbeatRoute: ApiDevicesHeartbeatRoute,
  ApiNfcScanRoute: ApiNfcScanRoute,
  ApiPlayerDownloadRoute: ApiPlayerDownloadRoute,
  ApiPlayerVersionRoute: ApiPlayerVersionRoute,
  ApiStreamSongIdRoute: ApiStreamSongIdRoute,
  ApiStreamEpisodeEpisodeIdRoute: ApiStreamEpisodeEpisodeIdRoute,
  ApiDevicesRegisterIndexRoute: ApiDevicesRegisterIndexRoute,
  ApiDevicesRegisterDeviceIdSshReadyRoute:
    ApiDevicesRegisterDeviceIdSshReadyRoute,
  ApiDevicesRegisterDeviceIdStatusRoute: ApiDevicesRegisterDeviceIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
