/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/_library'
import { Route as LibraryIndexRouteImport } from './routes/_library/index'
import { Route as LibraryCardsRouteImport } from './routes/_library/cards'
import { Route as ApiStreamSongIdRouteImport } from './routes/api/stream/$songId'
import { Route as LibraryPlaylistIdRouteImport } from './routes/_library/playlist.$id'

const LibraryRoute = LibraryRouteImport.update({
  id: '/_library',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryCardsRoute = LibraryCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => LibraryRoute,
} as any)
const ApiStreamSongIdRoute = ApiStreamSongIdRouteImport.update({
  id: '/api/stream/$songId',
  path: '/api/stream/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPlaylistIdRoute = LibraryPlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/cards': typeof LibraryCardsRoute
  '/': typeof LibraryIndexRoute
  '/playlist/$id': typeof LibraryPlaylistIdRoute
  '/api/stream/$songId': typeof ApiStreamSongIdRoute
}
export interface FileRoutesByTo {
  '/cards': typeof LibraryCardsRoute
  '/': typeof LibraryIndexRoute
  '/playlist/$id': typeof LibraryPlaylistIdRoute
  '/api/stream/$songId': typeof ApiStreamSongIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_library': typeof LibraryRouteWithChildren
  '/_library/cards': typeof LibraryCardsRoute
  '/_library/': typeof LibraryIndexRoute
  '/_library/playlist/$id': typeof LibraryPlaylistIdRoute
  '/api/stream/$songId': typeof ApiStreamSongIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/cards' | '/' | '/playlist/$id' | '/api/stream/$songId'
  fileRoutesByTo: FileRoutesByTo
  to: '/cards' | '/' | '/playlist/$id' | '/api/stream/$songId'
  id:
    | '__root__'
    | '/_library'
    | '/_library/cards'
    | '/_library/'
    | '/_library/playlist/$id'
    | '/api/stream/$songId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LibraryRoute: typeof LibraryRouteWithChildren
  ApiStreamSongIdRoute: typeof ApiStreamSongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_library': {
      id: '/_library'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/': {
      id: '/_library/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/_library/cards': {
      id: '/_library/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof LibraryCardsRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/api/stream/$songId': {
      id: '/api/stream/$songId'
      path: '/api/stream/$songId'
      fullPath: '/api/stream/$songId'
      preLoaderRoute: typeof ApiStreamSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/playlist/$id': {
      id: '/_library/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof LibraryPlaylistIdRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface LibraryRouteChildren {
  LibraryCardsRoute: typeof LibraryCardsRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  LibraryPlaylistIdRoute: typeof LibraryPlaylistIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryCardsRoute: LibraryCardsRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  LibraryPlaylistIdRoute: LibraryPlaylistIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LibraryRoute: LibraryRouteWithChildren,
  ApiStreamSongIdRoute: ApiStreamSongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
