/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSongsRouteImport } from './routes/admin/songs'
import { Route as AdminPlaylistsRouteImport } from './routes/admin/playlists'
import { Route as AdminLibraryRouteImport } from './routes/admin/library'
import { Route as AdminDownloadsRouteImport } from './routes/admin/downloads'
import { Route as AdminCardsRouteImport } from './routes/admin/cards'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSongsRoute = AdminSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlaylistsRoute = AdminPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDownloadsRoute = AdminDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCardsRoute = AdminCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/cards': typeof AdminCardsRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/songs': typeof AdminSongsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/cards': typeof AdminCardsRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/songs': typeof AdminSongsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/cards': typeof AdminCardsRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/songs': typeof AdminSongsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/cards'
    | '/admin/downloads'
    | '/admin/library'
    | '/admin/playlists'
    | '/admin/songs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/cards'
    | '/admin/downloads'
    | '/admin/library'
    | '/admin/playlists'
    | '/admin/songs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/cards'
    | '/admin/downloads'
    | '/admin/library'
    | '/admin/playlists'
    | '/admin/songs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/songs': {
      id: '/admin/songs'
      path: '/songs'
      fullPath: '/admin/songs'
      preLoaderRoute: typeof AdminSongsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/playlists': {
      id: '/admin/playlists'
      path: '/playlists'
      fullPath: '/admin/playlists'
      preLoaderRoute: typeof AdminPlaylistsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/downloads': {
      id: '/admin/downloads'
      path: '/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AdminDownloadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cards': {
      id: '/admin/cards'
      path: '/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AdminCardsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCardsRoute: typeof AdminCardsRoute
  AdminDownloadsRoute: typeof AdminDownloadsRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminPlaylistsRoute: typeof AdminPlaylistsRoute
  AdminSongsRoute: typeof AdminSongsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCardsRoute: AdminCardsRoute,
  AdminDownloadsRoute: AdminDownloadsRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminPlaylistsRoute: AdminPlaylistsRoute,
  AdminSongsRoute: AdminSongsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
